#!/bin/bash
pip install -r requirements.txt
python3 manage.py makemigrations
python3 manage.py migrate
python manage.py createsuperuser --username admin --email admin@example.com --noinput
python manage.py changepassword admin
python3 manage.py runserver